config/routes.rb
Teacherforme::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "/me" => "users#me", :as => 'me'

  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations"} do
  end

  get "check_email" => "api#check_email", :as => "check_email"

  resources :teachers do 
    get "/complete" => "teachers#complete", :as => "complete", :on => :member
    get "/incomplete" => "teachers#incomplete", :as => "incomplete", :on => :member
  end

  resources :students do
    get "/complete" => "students#complete", :as => "complete", :on => :member
    get "/incomplete" => "students#incomplete", :as => "incomplete", :on => :member
  end

  get "about" => "main#about", :as => "about"
  get "help" => "main#help", :as => "help"

  resources :replies

  root :to => 'main#index'

end

app/models/user.rb
class User
  include Mongoid::Document
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  ## Database authenticatable
  field :email,              :type => String, :null => false, :default => ""
  field :encrypted_password, :type => String, :null => false, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Encryptable
  # field :password_salt, :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  ## Token authenticatable
  # field :authentication_token, :type => String


  field :phone,   :type => String

  has_many :teachers, dependent: :delete
  has_many :students, dependent: :delete

end

app/controllers/users_controller.rb
#coding: utf-8
class UsersController < ApplicationController
  before_filter :authenticate_user!

  def me
    @user = current_user
    @teachers = current_user.teachers.desc('created_at')
    @students = current_user.students.desc('created_at')
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_student.html.erb
<tr>
  <td style="position: relative">
    저는 <b><%= student.sex ? "여자" : "남자" %></b>고
    <b><%= student.subject %></b> 을/를 배우길 원합니다!<br />
    <b><%= student.want_sex_str %></b>선생님을 원하고요, 보수는 <b><%= student.pay %></b>만원 이상 드릴 생각이 있습니다.<br />
    지역은 <b><%= student.location %></b> 이고 나이는
    <b><%= student.year_str %></b>
    입니다.<br />
    <b><%= student.comment %></b><br />
    연락주세요!!
    <%= link_to '수정하기', edit_student_path(student) %>
    <% if student.complete? %>
      <%= link_to '진행중으로 만들기', incomplete_student_path(student) %>
      <br /><span class="label label-success">완료</span>
    <% else -%>
      <%= link_to '완료로 만들기', complete_student_path(student) %>
      <br /><span class="label label-warning">진행중</span>
    <% end -%>
  </td>
</tr>

app/views/users/_teacher.html.erb
<tr>
  <td style="position: relative;">
    저는 <b><%= teacher.sex ? "여자" : "남자" %></b> 선생님 이고 <b><%= teacher.age %></b>살이며
    <b><%= teacher.subject %></b> 과목을 가르칠 수 있습니다.<br />
    가르칠 수 있는 대상은 <b><%= teacher.year_str %> <%= teacher.want_sex_str %></b>이고 
    가르칠 수 있는 지역은 <b><%= teacher.location %></b> 이에요.<br />
    보수로는 <b><%= teacher.pay %></b>만원 (8회 2시간씩 기준) 이상을 원하고 
    <%= teacher.comment %><br />
    연락주세요 ^^!
    <%= link_to '수정하기', edit_teacher_path(teacher) %>
    <% if teacher.complete? %>
      <%= link_to '진행중으로 만들기', incomplete_teacher_path(teacher) %>
      <br /><span class="label label-success">완료</span>
    <% else -%>
      <%= link_to '완료로 만들기', complete_teacher_path(teacher) %>
      <br /><span class="label label-warning">진행중</span>
    <% end -%>
  </td>
</tr>

app/views/users/me.html.erb
<h2><%= current_user.email %>님의 페이지입니다.</h2>

<h3>My Contact Info</h3>
<%= form_tag user_registration_path, :method => "put" do %>
  <%= label_tag "user[phone]", "Phone Number" %>
  <%= text_field_tag "user[phone]", current_user.phone %>
  <%= submit_tag '수정하기' %>
<% end -%>

<h3>My Info as Teacher</h2>

<table class="table table-striped" style="width: 100%">
  <tbody>
    <%= render :partial => "users/teacher", :collection => @teachers %>
  </tbody>
</table>
<h3>My Info as Student</h2>
<table class="table table-striped" style="width: 100%">
  <tbody>
    <%= render :partial => "users/student", :collection => @students %>
  </tbody>
</table>