config/routes.rb
Teacherforme::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "/me" => "users#me", :as => 'me'

  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations"} do
  end

  get "check_email" => "api#check_email", :as => "check_email"

  resources :teachers do 
    get "/complete" => "teachers#complete", :as => "complete", :on => :member
    get "/incomplete" => "teachers#incomplete", :as => "incomplete", :on => :member
  end

  resources :students do
    get "/complete" => "students#complete", :as => "complete", :on => :member
    get "/incomplete" => "students#incomplete", :as => "incomplete", :on => :member
  end

  get "about" => "main#about", :as => "about"
  get "help" => "main#help", :as => "help"

  resources :replies

  root :to => 'main#index'

end

app/models/teacher.rb
#coding: utf-8
class Teacher
  include Mongoid::Document
  include Mongoid::Timestamps

  YEAR_HASH = {"ele" => "초등", "mid1" => "중1", "mid2" => "중2", "mid3" => "중3", "high1" => "고1", "high2" => "고2", "high3" => "고3", "general" => "일반"}
  ELEMENTRY = ["ele","초등"]
  MIDDLE1 = ["mid1","중1"]
  MIDDLE2 = ["mid2","중2"]
  MIDDLE3 = ["mid3","중3"]
  HIGH1 = ["high1","고1"]
  HIGH2 = ["high2","고2"]
  HIGH3 = ["high3","고3"]
  GENERAL = ["general","일반"]

  field :year, type: Array # Student's age

  field :pay, type: Integer
  field :age, type: Integer
  field :sex, type: Boolean
  field :want_sex, type: Integer
  field :subject
  field :location
  field :comment
  field :confirmed, type: Boolean, default: false
  field :complete, type: Boolean, default: false

  belongs_to :university
  belongs_to :user
  has_many :replies, as: :receiver

  def confirmed?
    self.confirmed
  end

  def want_sex_str
    if self.want_sex == 0
      "남녀모두"
    elsif self.want_sex == 1
      "여자"
    else
      "남자"
    end
  end
  def year_str
    res = ""
    if self.year
      self.year.each do |y|
        res << YEAR_HASH[y]+","
      end
    end
    res
  end

  def contact(current_user, message)
    ContactMailer.contact_to_teacher_email(current_user,self,message).deliver
  end

end

app/controllers/teachers_controller.rb
#coding : utf-8
class TeachersController < ApplicationController
  before_filter :authenticate_user!, :only => [:contact]
  before_filter :find_or_create_user, :only => [:create]

  def index
    @teachers = Teacher.where(:confirmed => true, :complete => false)
  end
  def create
    @teacher = Teacher.new(params[:teacher])
    @teacher.user = @user
    if @user.confirmed?
      @teacher.confirmed = true
    end
    if @teacher.save
      flash[:success] = "선생님 정보가 생성되었습니다."
      unless @teacher.user.confirmed?
        flash[:info] = "적어주신 이메일주소로 확인메일이 전송됩니다. 인증후 목록에 보이게 됩니다."
      end
      redirect_to teachers_path
    else
      flash[:error] = "선생님 정보가 생성되지 않았습니다."
      redirect_to root_path
    end
  end

  def edit
    @teacher = Teacher.find params[:id]
  end

  def update
    @teacher = Teacher.find params[:id]
    if @teacher.update_attributes params[:teacher]
      flash[:success] = "성공적으로 수정되었습니다."
      redirect_to me_path
    else
      flash[:error] = "수정중에 오류가 발생했습니다."
      redirect_to me_path
    end
  end

  def incomplete
    @teacher = Teacher.find params[:id]
    @teacher.update_attribute(:complete, false)
    redirect_to me_path
  end
  def complete
    @teacher = Teacher.find params[:id]
    @teacher.update_attribute(:complete, true)
    redirect_to me_path
  end

  private

  def find_or_create_user
    if User.where(:email => params[:teacher_email]).count > 0
      @user = User.where(:email => params[:teacher_email]).first
      if @user.valid_password?(params[:teacher_password])
        @user.phone = params[:teacher_phone]
        @user.save
        current_user = @user
      else
        flash[:error] = "Wrong password"
        redirect_to root_path and return
      end
    else
      unless params[:teacher_new_password] == params[:teacher_password_confirmation]
        flash[:error] = "Password and Password Confirmation are not same"
        redirect_to root_path and return
      end
      @user = User.new(:email => params[:teacher_email], :password => params[:teacher_new_password], :password_confirmation => params[:teacher_password_confirmation], :phone => params[:teacher_phone])
      unless @user.save
        flash[:error] = "User was not created"
        redirect_to root_path and return
      end
    end
  end


end

app/helpers/teachers_helper.rb
module TeachersHelper
  def checklabel_tag(name_const,label_name)
    return check_box_tag("teacher[year][]", name_const, nil, :id => "teacher_year_#{name_const}")\
    +label_tag("teacher_year_#{name_const}", label_name, :style => "display: inline;")
  end
end

app/views/teachers/_teacher.html.erb
<tr>
  <td style="position: relative;">
    저는 <b><%= teacher.sex ? "여자" : "남자" %></b> 선생님 이고 <b><%= teacher.age %></b>살이며
    <b><%= teacher.subject %></b> 과목을 가르칠 수 있습니다.<br />
    가르칠 수 있는 대상은 <b><%= teacher.year_str %> <%= teacher.want_sex_str %></b>이고 
    가르칠 수 있는 지역은 <b><%= teacher.location %></b> 이에요.<br />
    보수로는 <b><%= teacher.pay %></b>만원 (8회 2시간씩 기준) 이상을 원하고 
    <%= teacher.comment %><br />
    연락주세요 ^^!
    <%= form_tag replies_path, :remote => true do %>
      <%= hidden_field_tag "type", "teacher" %>
      <%= hidden_field_tag "receiver_id", teacher.id.to_s %>
      <div class="contact_form"><%= text_area_tag "reply[comment]", nil, :rows => 4, :placeholder => "전달하고싶은 말을 간단히 적어주세요." %></div>
      <%= submit_tag '연락하기', :class => "btn sendContact" %>
    <% end -%>
  </td>
</tr>

app/views/teachers/edit.html.erb
<%= form_for @teacher, :html => { :class => "well", :style => "margin-top: 15px;"} do |f| %>
  <h1 style="margin-top: 10px; margin-bottom: 10px;">저는 책임감 있는 선생님이고 지금 학생을 구하고 있어요</h1>
  저는 <%= f.select :sex, '<option value="true">여자</option><option value="false">남자</option>'.html_safe %> 선생님 이고 <%= f.number_field :age %>살이며 
  <%= f.text_field :subject, :placeholder => "ex) 수학, 영어" %> 과목을 가르칠 수 있습니다.<br />
  가르칠 수 있는 대상은 
  <%# checklabel_tag in teachers helper -%>
  <%= checklabel_tag(Teacher::ELEMENTRY[0], Teacher::ELEMENTRY[1]) %>
  , <%= checklabel_tag(Teacher::MIDDLE1[0], Teacher::MIDDLE1[1]) %>
  , <%= checklabel_tag(Teacher::MIDDLE2[0], Teacher::MIDDLE2[1]) %>
  , <%= checklabel_tag(Teacher::MIDDLE3[0], Teacher::MIDDLE3[1]) %>
  , <%= checklabel_tag(Teacher::HIGH1[0], Teacher::HIGH1[1]) %>
  , <%= checklabel_tag(Teacher::HIGH2[0], Teacher::HIGH2[1]) %>
  , <%= checklabel_tag(Teacher::HIGH3[0], Teacher::HIGH3[1]) %>
  , <%= checklabel_tag(Teacher::GENERAL[0], Teacher::GENERAL[1] ) %>
  <%= f.select :want_sex, '<option value="0">남녀모두</option><option value="1">여자</option><option value="2">남자</option>'.html_safe %>이고 <br />
  가르칠 수 있는 지역은 <%= f.text_field :location, :placeholder => "ex) 서울, 경기, 대학동" %> 이에요.<br />
  보수로는 <%= f.number_field :pay %>만원 (8회 2시간씩 기준) 이상을 원하고<br />
  <%= f.text_area :comment, :rows => 3, :placeholder => "한마디 ex) 학생을 성실히 지도할것입니다.", :style => "width: 400px;" %><br />
  <%= f.submit '수정하기', :class => "btn btn-success", :style => "width: 200px; height: 30px;" %>
<% end -%>

app/views/teachers/index.html.erb
<div>
  <table class="table table-striped" style="width: 100%">
    <tbody id="teachers">
      <%= render @teachers %>
    </tbody>
  </table>
</div>