config/routes.rb
Teacherforme::Application.routes.draw do

  mount RailsAdmin::Engine => '/admin', :as => 'rails_admin'

  get "/me" => "users#me", :as => 'me'

  devise_for :users, :controllers => {:registrations => "registrations", :confirmations => "confirmations"} do
  end

  get "check_email" => "api#check_email", :as => "check_email"

  resources :teachers do 
    get "/complete" => "teachers#complete", :as => "complete", :on => :member
    get "/incomplete" => "teachers#incomplete", :as => "incomplete", :on => :member
  end

  resources :students do
    get "/complete" => "students#complete", :as => "complete", :on => :member
    get "/incomplete" => "students#incomplete", :as => "incomplete", :on => :member
  end

  get "about" => "main#about", :as => "about"
  get "help" => "main#help", :as => "help"

  resources :replies

  root :to => 'main#index'

end

app/views/layouts/_nav_bar.html.erb
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="brand" href="/">
        Teacher for Me
      </a>
      <ul class="nav">
        <li<%= params[:controller]=="teachers" ? ' class=active' : '' %>><a href="<%= teachers_path %>">선생님들</a></li>
        <li<%= params[:controller]=="students" ? ' class=active' : '' %>><a href="<%= students_path %>">학생/학부모님들</a></li>
        <!--<li<%= params[:action]=="about" ? ' class=active' : '' %>><a href="<%= about_path %>">About</a></li> -->
        <li<%= params[:action]=="help" ? ' class=active' : '' %>><a href="<%= help_path %>">도움말</a></li>
        <% if user_signed_in? -%>
          <li><%= link_to '관리', me_path %></li>
        <% end -%>
        <li class="dropdown">
          <%= user_signed_in? ? link_to('로그아웃', destroy_user_session_path, :method => :delete) : link_to('로그인', new_user_session_path) %>
        </li>
      </ul>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Teacher for me</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body style="padding-top: 45px;">
  <%= render 'layouts/nav_bar' %>
  <% if flash[:error] -%>
    <div class="alert alert-error">
      <a class="close" data-dismiss="alert">x</a>
      <strong>오류가 발생했어요! : </strong><%= flash[:error] %>
    </div>
  <% end -%>
  <% if flash[:success] -%>
    <div class="alert alert-success">
      <a class="close" data-dismiss="alert">x</a>
      <%= flash[:success] %>
    </div>
  <% end -%>
  <% if flash[:info] -%>
    <div class="alert alert-info">
      <a class="close" data-dismiss="alert">x</a>
      <strong>Help : </strong><%= flash[:info] %>
    </div>
  <% end -%>
  <div class="container">

  <%= yield %>

  </div>
</body>
</html>